### ISSUE TITLE
[Feature request] Pre-compiled Windows Binary

### ISSUE THREAD

**Issue by RyanBram** [pornel/mediancut-posterizer#8]
Hi, Kornel.
I like most of your work. But unfortunately as a non programmer, i don't know how to compile a program. If you want to provide, it will be pleasure.

Thanks

**Comment by pornel** [comment]
See downloads https://github.com/pornel/mediancut-posterizer/releases #6

**Comment by sergeevabc** [comment]
posterizer-Windows.zip 1.6 has no -b option and seems quite outdated, would you mind updating it, please?
